### ISSUE TITLE
ImportError: cannot import name 'CreateDataLoader' 

### ISSUE THREAD

**Issue by zhibo-liu** [junyanz/VON#1]
Thank you so much for sharing your code. However, it seems that some of your scripts are missing. I cannot find `CreateDataLoader` module. And there is no `./data` subfolder.

**Comment by lxj616** [comment]
wget http://von.csail.mit.edu/data/data.tar
tar -xvf data.tar ./

**Comment by zhibo-liu** [comment]
I already download `data.tar` . It only contains dataset instead of python script.
```bash
data
├── images
│   ├── car
│   └── chair
└── objects
    ├── df
    │   ├── car
    │   └── chair
    └── voxel
        ├── car
        └── chair
```

**Comment by lxj616** [comment]
hmmm, could we borrow the data folder from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix ?

**Comment by zhibo-liu** [comment]
I don't think so. I guess we have wait for @junyanz  to fix it.

**Comment by wuxiao111** [comment]
Have you solved this problem?

**Comment by junyanz** [comment]
I added the data loader and updated the instructions. Sorry for the delay.
