### ISSUE TITLE
How can I get and view (or render) distance function grids in 3D view?

### ISSUE THREAD

**Issue by fangqiaohu** [junyanz/VON#10]
Thanks to your awesome work! Generating images from 3D is a great idea!

You demonstrated some images of distance function grids in your paper, but there seems no code doing this, sorry I'm new to 3D learning.  

I‘m wondering how to get distance functions from a mesh like *.obj files, and how to render such a N x N x N distance grid in 3D view (just like your paper). Can you provide some tools or just tell me the name?

**Comment by ztzhang** [comment]
Hi,

Thanks for your interest in our paper!
To generate the training distance functions, we first densely sample a large amount of points on the obj mesh, then discretize the 3D space into voxel grids. To generate distance functions, one can query the k-nearest points at the center of each voxel grid, and record the average distance to be the value at of that grid.

To visulize, you can refer to  [here](https://github.com/junyanz/VON/blob/46007d0af73cd23f9c2335d249113c8bf83cc661/util/util_voxel.py#L138) and [here](https://github.com/junyanz/VON/blob/46007d0af73cd23f9c2335d249113c8bf83cc661/util/util_voxel.py#L129) for saving voxels as obj files. We use (blender)[https://www.blender.org
] for rendering obj files.
