### ISSUE TITLE
how to construct the .npz training data?

### ISSUE THREAD

**Issue by Edwardmark** [junyanz/VON#12]
How to change the voxel value to distance function values?
What is the distance function you are actually using?
Could you elaborate how to change the shapenet file to your training data format?

**Comment by ztzhang** [comment]
The details for generating the DF dataset are as follows:

We first normalize each CAD model so that they are zero centered and scaled to fit into unit sphere. We then densely sample points for each CAD model on its surface, using furthest point sampling with L2 distance. Then, we discretize the 3D space into evenly spaced grids. For each grid center, we record its value as the mean L2 distance between its center and its k-nearest points. We use k=5 for a more smoothed DF.

Hope this helps!

**Comment by Edwardmark** [comment]
@ztzhang Could you provide some code about it? It seems difficult to understand for me. 
For example, when I get the obj file of shapenet, how can I generate the .npz data? Any code please?Thank you.

**Comment by ztzhang** [comment]
Since this is suppose to be the a plugin for one of our server cluster tools, I'll just paste it here instead of adding it to the repo. Not tested off the shelf though, but it should work.
```python
import os
import sys
from os.path import join, exists
import argparse
import trimesh
import scipy
import numpy as np


def parse_args(commands):
    parser = argparse.ArgumentParser(
        description='generate_spherical_representations')
    parser.add_argument('path', type=str, help="path to obj")
    parser.add_argument("-o", "--overwrite",
                        action="store_true", help="overwite previous result")
    args = parser.parse_args(commands)
    return args


def main(argv, lock=None):
    from contextlib import redirect_stderr
    import io
    f = io.StringIO()
    with redirect_stderr(f):
        opt = parse_args(argv)
        obj_path = opt.path
        save_path = join(os.path.dirname(obj_path), 'df')
        if exists(save_path + '.npz') and not opt.overwrite:
            return 0
        res = 128
        density = 80000
        mesh = trimesh.load(obj_path)
        mesh.vertices -= mesh.centroid
        x = np.linspace(-0.5, 0.5, res)
        xv, yv, zv = np.meshgrid(x, x, x)
        points = np.zeros([res, res, res, 3])
        points[:, :, :, 0] = xv
        points[:, :, :, 1] = yv
        points[:, :, :, 2] = zv
        points = points.reshape(res**3, 3)
        mesh_points = mesh.sample(int(mesh.area * density))
        tree = scipy.spatial.cKDTree(mesh_points, leafsize=30)
        d, _ = tree.query(points, k=5)
        d = np.mean(d, 1)
        d_s = d.reshape(res, res, res)
        if lock:
            lock.acquire()
        np.savez(save_path, df=np.float32(d_s))
        if lock:
            lock.release()
    print(f.getvalue())
    return 0


if __name__ == '__main__':
    main(sys.argv)
```

**Comment by Edwardmark** [comment]
@ztzhang what is the lib contextlib?

**Comment by Edwardmark** [comment]
I try to load an obj file using your code, but it occurs following error as:
>>> import trimesh
>>> trimesh.load('./02843684/1025dd84537d737febed407fccfaf6d8/model.obj')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/exchange/load.py", line 135, in load
    **kwargs)
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/constants.py", line 128, in timed
    result = method(*args, **kwargs)
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/exchange/load.py", line 219, in load_mesh
    loaded.append(load_kwargs(kwargs))
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/exchange/load.py", line 438, in load_kwargs
    return handler()
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/exchange/load.py", line 404, in handle_trimesh_kwargs
    return Trimesh(**kwargs)
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/base.py", line 176, in __init__
    self.process()
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/base.py", line 208, in process
    self.merge_vertices()
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/base.py", line 1023, in merge_vertices
    textured=textured)
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/trimesh/grouping.py", line 56, in merge_vertices
    mesh.visual.uv * (10 ** uv_digits))).round().astype(np.int64)
  File "/home/user/miniconda/envs/von/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 594, in column_stack
    return _nx.concatenate(arrays, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

Have you met this error before? Did I miss sth? It seems like some format is wrong. Could you help me out? Thx.

**Comment by scamper07** [comment]
Hi @ztzhang 
Could you tell me the versions of python and trimesh used here?

I get few error with the latest trimesh (obj file gets loaded as Scene object instead of Trimesh object)
Followed few workarounds from [https://github.com/mikedh/trimesh/issues/507](https://github.com/mikedh/trimesh/issues/507), but the code hangs at mesh.sample statement and my system memory usage spikes.

Thank you

**Comment by ztzhang** [comment]
I think we used trimesh=2.35.47
