### ISSUE TITLE
Questions about the details about the training data.

### ISSUE THREAD

**Issue by Edwardmark** [junyanz/VON#13]
I met some problem when try to train VON, 
1. how to generate .npz data from shapenet dataset? Which dataset are you using, the 2016 voxels data or the shapenetcore .obj data?
2. what is the training img for training texture gan? And how you generate it?

Can you show me a easy example with sample and code? Thank you very much.
BTW, could you upload you data.tar to google drive or OneDrive? The link in your script is much too slow. Thank you very much again.

**Comment by ztzhang** [comment]
1. obj files
2. images are crawled from google.


You should be able to access the data [here(dropbox)](https://www.dropbox.com/s/onaeyeiioq6vfkz/data.tar?dl=0). I'm still uploading, should be done in 20 min or so.
A sample code can be found [here](https://github.com/junyanz/VON/issues/12)

**Comment by Edwardmark** [comment]
@ztzhang Thank you very much for your quick respond and patience. Great job.
