### ISSUE TITLE
Error occurs when running "bash ./scripts/figures.sh 0 car df". ModuleNotFoundError: No module named 'vtn'.

### ISSUE THREAD

**Issue by LYHTHU** [junyanz/VON#14]
It shows 
`ModuleNotFoundError: No module named 'vtn'`
However, the compilation succeeds. It only raises several WARNING but no errors in the compilation. And I run this code in the virtual env "von" initialized as the instruction.

**Comment by junyanz** [comment]
Have you followed the [README](https://github.com/junyanz/VON#getting-started) and compile the code? 
Have you compiled the kernels? 
```bash
bash install.sh
```

**Comment by LYHTHU** [comment]
Yes. I run the bash ./install.sh. And it succeeds(though raises several warnings).

**Comment by ztzhang** [comment]
@LYHTHU would you mind providing more details? For example:

- Can you find the compiled .so file in vtn/vtn/src? 

- Import vtn by enforcing absolute path? i.e. append the path to sys.path?

It seems I could not reproduce this problem, which is a bit weird.

**Comment by LYHTHU** [comment]
@ztzhang  Really thanks for your reply. Sorry for the late reply. I was busy taking a course then.

I can only find "_vtn_lib.so" in "vtn/vtn/_ext/vtn_lib". No .so files in the "vtn/vtn/src". I have not tried the absolute import yet.
The error info is as follows:

```Traceback (most recent call last):
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/render_module/render_sketch.py", line 2, in <module>
    from .vtn.vtn.functions import grid_sample3d, affine_grid3d
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/render_module/vtn/vtn/functions/__init__.py", line 2, in <module>
    from .grid_sample3d import grid_sample3d
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 3, in <module>
    from .._ext import vtn_lib
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/render_module/vtn/vtn/_ext/vtn_lib/__init__.py", line 3, in <module>
    from ._vtn_lib import lib as _lib, ffi as _ffi
ImportError: /home/yunhaoli/Desktop/Graphics_Research/VON/render_module/vtn/vtn/_ext/vtn_lib/_vtn_lib.so: undefined symbol: __cudaPopCallConfiguration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = create_model(opt)
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/models/__init__.py", line 59, in create_model
    instance = model(opt)
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/models/test_model.py", line 34, in __init__
    self.setup_DR(opt)
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/models/base_model.py", line 159, in setup_DR
    from render_module.render_sketch import VoxelRenderLayer, CroppingLayer, GetRotationMatrix, FineSizeCroppingLayer
  File "/home/yunhaoli/Desktop/Graphics_Research/VON/render_module/render_sketch.py", line 4, in <module>
    from vtn.vtn.functions import grid_sample3d, affine_grid3d
ModuleNotFoundError: No module named 'vtn'
```

**Comment by ztzhang** [comment]
@LYHTHU Hi, Would you mind sharing the CUDA version you are currently using?

**Comment by LYHTHU** [comment]
> @LYHTHU Hi, Would you mind sharing the CUDA version you are currently using?

I am using CUDA 10.0.

**Comment by ztzhang** [comment]
It seems I can reproduce this under CUDA 10.0. However, everything seems to work fine with older CUDA Versions (9.0 and 8.0).

One fix is to use older cuda versions,  which might be a bit troublesome. I'm still testing a piece of code that replaces the custom kernels with pytorch built-in functions. I should be able to push it in couple of days. 

Thanks for bringing up this issue!  I'll update this issue once the replacement is in place.

**Comment by LYHTHU** [comment]
@ztzhang  I just try to run the code on my other machine installed with CUDA 9.1. However it still failed.
The error info is as follows:
```
error in BilinearSampler3D update output: invalid device function
Traceback (most recent call last):
  File "test.py", line 58, in <module>
    image, depth, mask = model.sample_2d(view_id=k, extra=True)
  File "/home/yunhaoli/Desktop/Research/VON/models/test_model.py", line 115, in sample_2d
    self.mask, self.depth = self.get_depth(self.voxel, self.rot_mat, use_df=self.use_df)
  File "/home/yunhaoli/Desktop/Research/VON/models/base_model.py", line 262, in get_depth
    silhouette_orig, depth_orig = self.renderLayer(voxel, rot_mat)
  File "/home/yunhaoli/anaconda3/envs/von/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yunhaoli/Desktop/Research/VON/render_module/render_sketch.py", line 249, in forward
    voxel_rot = self.grid_sampler3d(voxel_in, voxel_rot_grid)
  File "/home/yunhaoli/Desktop/Research/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 62, in grid_sample3d
    return GridSampler3D.apply(input, grid)
  File "/home/yunhaoli/Desktop/Research/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 35, in forward
    getattr(vtn_lib, func_name)(input, grid, output)
  File "/home/yunhaoli/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 202, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: aborting at /home/yunhaoli/Desktop/Research/VON/render_module/vtn/vtn/src/generic/vtn_cuda_generic.c:15
```

**Comment by hakanyi** [comment]
@ztzhang Thanks for looking into this issue! Can you estimate when you would be able to push the replacements?

**Comment by Everbeast** [comment]
> @ztzhang I just try to run the code on my other machine installed with CUDA 9.1. However it still failed.
> The error info is as follows:
> 
> ```
> error in BilinearSampler3D update output: invalid device function
> Traceback (most recent call last):
>   File "test.py", line 58, in <module>
>     image, depth, mask = model.sample_2d(view_id=k, extra=True)
>   File "/home/yunhaoli/Desktop/Research/VON/models/test_model.py", line 115, in sample_2d
>     self.mask, self.depth = self.get_depth(self.voxel, self.rot_mat, use_df=self.use_df)
>   File "/home/yunhaoli/Desktop/Research/VON/models/base_model.py", line 262, in get_depth
>     silhouette_orig, depth_orig = self.renderLayer(voxel, rot_mat)
>   File "/home/yunhaoli/anaconda3/envs/von/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yunhaoli/Desktop/Research/VON/render_module/render_sketch.py", line 249, in forward
>     voxel_rot = self.grid_sampler3d(voxel_in, voxel_rot_grid)
>   File "/home/yunhaoli/Desktop/Research/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 62, in grid_sample3d
>     return GridSampler3D.apply(input, grid)
>   File "/home/yunhaoli/Desktop/Research/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 35, in forward
>     getattr(vtn_lib, func_name)(input, grid, output)
>   File "/home/yunhaoli/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 202, in safe_call
>     result = torch._C._safe_call(*args, **kwargs)
> torch.FatalError: aborting at /home/yunhaoli/Desktop/Research/VON/render_module/vtn/vtn/src/generic/vtn_cuda_generic.c:15
> ```

i met the same issue "torch.FatalError:.....vtn_cuda_generic.c:15" 
have you solved the problem?  thanks
