### ISSUE TITLE
Meet bug when using multi-gpu training

### ISSUE THREAD

**Issue by ZwwWayne** [junyanz/VON#23]
Hi @ztzhang & @junyanz ,

Thanks for the great work with the great code.

I tried to use multi-GPU training recently, it seems that the training will down at the end of one epoch, as shown in the following picture
![image](https://user-images.githubusercontent.com/40779233/67139018-b8656f80-f27d-11e9-863b-12b505df2f6e.png)

My script is as the following
`python -u train.py --gpu_ids 0,1 --display_id 1000 --dataset_mode df --model 'shape_gan' --class_3d car --checkpoints_dir ${CHECKPOINTS_DIR} --niter 125 --niter_decay 125 --batch_size 16 --G_norm_3D inst3d  --save_epoch_freq 10 --suffix {class_3d}_{model}_{dataset_mode} `

My guess is that the training data has 3457 samples and 3457%16 = 1, thus at the last iteration, only one GPU got the sample while another one did not.

I am not sure whether the guess is right,  so do you have any suggestions or solution to fix this bug?

**Comment by ztzhang** [comment]
you can try setting the droplast argument to be True for the dataloader.
This will simply drop the last batch.

**Comment by ZwwWayne** [comment]
Thank you, I am trying now.

**Comment by ZwwWayne** [comment]
Hi Zhoutong @ztzhang , it seems that setting drop_last=True could solve this problem. 
Thank you very much!
