### ISSUE TITLE
Using CPU only

### ISSUE THREAD

**Issue by hakanyi** [junyanz/VON#26]
I've been trying to run the pipeline (only testing, no training) using a CPU only. Was this repository intended to do so? 
In the readme it says that blender is optional and I interpreted it as blender being an alternative to the custom render module based on cuda. However, blender only seems to use whatever model.sample_2d() outputs and model.sample_2d() in turn is based on the custom render module.
Thanks in advance for commenting on this!

**Comment by junyanz** [comment]
Not sure if it works for CPU, as the custom render module requires CUDA. The blender is NOT an alternative to the custom module. The blender is used for visualization,  while the custom module is used for training.

**Comment by ztzhang** [comment]
I think the current version does not support CPU-only training/testing. The custom CUDA kernel is used during the generation process, therefore you have to use GPU for testing.

**Comment by hakanyi** [comment]
Thanks for clarifying!
