### ISSUE TITLE
CUDA out of memory issue on training 2D Texture Network

### ISSUE THREAD

**Issue by scamper07** [junyanz/VON#27]
Hi,
Thank you for the code and the detailed installation procedure.

I needed some information on the training steps for the car use case.
We have the Quadro RTX 4000 GPU with 8 GB GDDR6 GPU memory. But on running the training for 2D texture network, it quickly uses up the memory and i have CUDA out of memory issue.
I kept reducing the dataset and finally was able to give only 10 images for training.

What was the hardware that you used for training and did you do any extra config for training 2605 images for the texture network?
Also can you suggest any steps to increase dataset without hitting the GPU memory issue.
I'm using PyTorch 0.4.1 with CUDA92 within conda

Thank you

**Comment by ztzhang** [comment]
Hi, what batch size are you using and what are the resolution of your training images?
The size of the dataset is not relevant to memory usage since only batches of them are loaded each time.

**Comment by scamper07** [comment]
I'm using the default batch size i.e 12.
I'm trying to train with the same car dataset so the resolution is the same.

**Comment by ztzhang** [comment]
I think most of our training is done with a 12GB RAM GPU. It should be fine if you lower the batch size, to 10 for example.

**Comment by junyanz** [comment]
Yeah, I will try 8 to 10.

**Comment by scamper07** [comment]
Thank you so much. Batch size of 8 worked
