### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by LV0913** [junyanz/VON#28]
Hello,I have trouble in downloading your pretrained models and dataset.It's too slow.And I can not open your dropbox link.Can you provide Baidu SkyDrive link or some way easy to get in Chinese Mainland?Thank you!

**Comment by junyanz** [comment]
The models and datasets are hosted at the MIT server. Maybe you want to try different downloading software. Sorry that we don't have additional servers or online storage.

**Comment by LV0913** [comment]
OK，I will try other way later.Thanks.
