### ISSUE TITLE
Where's the viewpoint code?

### ISSUE THREAD

**Issue by deepmo24** [junyanz/VON#7]
Hello,  I can't find the usage of viewpoint code in your source code,  I am not sure whether I ignore something, can you tell me about it? thank you.

**Comment by junyanz** [comment]
We get our viewpoint from the data loader. See this [line](https://github.com/junyanz/VON/blob/master/test.py#L23). 
We use it to render a 2.5D sketch (depth, mask) from a 3D model. See this [line](https://github.com/junyanz/VON/blob/master/models/test_model.py#L118).

**Comment by deepmo24** [comment]
Thank you very much.  I read section 3.2 "Generating 2.5D Sketches" of the paper again, and  now I understand it.

**Comment by junyanz** [comment]
This is great!
