### ISSUE TITLE
Can you provide a dockerfile to run the code?

### ISSUE THREAD

**Issue by Edwardmark** [junyanz/VON#9]
I run into several strange error in compiling the code, could you kindly provide a dockerfile of your system environment please?

**Comment by ztzhang** [comment]
@Edwardmark I added a dockerfile to the repo. I tested it with nvidia-docker2 to enable GPU support within the container. Please let me know if it works for you!

**Comment by Edwardmark** [comment]
@ztzhang Thanks man, I'll have it a try.
